# Generated by Django 4.2.2 on 2024-07-17 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_lesson_video_track'),
        ('users', '0002_alter_user_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='дата оплаты')),
                ('payment_method', models.CharField(blank=True, choices=[('CARD', 'картой'), ('CASH', 'наличными')], max_length=50, null=True, verbose_name='способ оплаты')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='ссылка для оплаты')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='идентификатор платежа')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course', verbose_name='оплаченный курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.lesson', verbose_name='оплаченный урок')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'платеж',
                'verbose_name_plural': 'платежы',
            },
        ),
    ]
