# Generated by Django 4.2.2 on 2024-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='summ',
            field=models.PositiveIntegerField(default=100, verbose_name='сумма платежа'),
        ),
    ]
