# Generated by Django 4.2.2 on 2024-07-10 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название курса', max_length=128, verbose_name='название курса')),
                ('description', models.TextField(blank=True, help_text='укажите описание учебного курса', null=True, verbose_name='описание учебного курса')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='course/images/', verbose_name='изображение')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель')),
            ],
            options={
                'verbose_name': 'учебный курс',
                'verbose_name_plural': 'учебные курсы',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='укажите название урока', max_length=128, verbose_name='название урока')),
                ('description', models.TextField(blank=True, help_text='укажите описание урока', null=True, verbose_name='описание урока')),
                ('image', models.ImageField(blank=True, help_text='загрузите изображение', null=True, upload_to='course/images/', verbose_name='изображение')),
                ('video_track', models.CharField(help_text='укажите ссылку на видео', max_length=256, verbose_name='видео')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.course', verbose_name='курс')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='cоздатель')),
            ],
            options={
                'verbose_name': 'урок',
                'verbose_name_plural': 'уроки',
            },
        ),
    ]
