# Generated by Django 4.2.2 on 2024-07-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_track',
            field=models.CharField(blank=True, help_text='укажите ссылку на видео', max_length=256, null=True, verbose_name='видео'),
        ),
    ]
